apiVersion: v1
kind: Service
metadata:
  name: ecom-service
spec:
  selector:
    app: ecom
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007  # Exposes the service on port 30007
  type: NodePort
