apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom
  template:
    metadata:
      labels:
        app: ecom
    spec:
      containers:
      - name: ecom
        image: robyn2022/ecom-app # Use your image name here
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: ecom-config
